networks:
  bridge_network:
    driver: bridge

  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_PARENT}
    ipam:
      config:
        - subnet: ${MACVLAN_SUBNET}
          gateway: ${MACVLAN_GATEWAY}

services:
  db:
    image: mysql:8.0.32
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bridge_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  fastapi_app:
    build: .
    container_name: api_ciclos_container
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      bridge_network:
      macvlan_network:
        ipv4_address: ${API_CICLOS_MACVLAN_IP}
  
  auth_app:
    build: 
      context: ../pf_pate_api_auth
      dockerfile: auth.Dockerfile
    container_name: api_auth_container
    restart: always
    depends_on:
      - fastapi_app
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      bridge_network:
      macvlan_network:
        ipv4_address: ${AUTH_MACVLAN_IP}
volumes:
  mysql_data: